[project]
name = "siscaixa"
version = "1.0.0"
description = "Sistema CLI de gestão de fluxo de caixa para MEIs"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "sqlalchemy",
    "typer",
    "requests",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
]

[project.scripts]
siscaixa = "siscaixa.cli.main:app"

[tool.ruff]
line-length = 79
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
]

[tool.pytest.ini_options]
pythonpath = ["."]
